export const GET_DATA_PHIM_THEOTRANG = 'GET_DATA_PHIM_THEOTRANG'


export const GET_DATA_PHIM_THEOTRANG_SAGA = 'GET_DATA_PHIM_THEOTRANG_SAGA'
export const DELETE_PHIM_SAGA = 'DELETE_PHIM_SAGA'
export const ADD_PHIM_SAGA = 'ADD_PHIM_SAGA'
export const ADD_IMG_PHIM_SAGA = 'ADD_PHIM_SAGA'

export const UPDATE_PHIM_SAGA = 'UPDATE_PHIM_SAGA'

export const UPDATE_IMG_PHIM_SAGA = 'UPDATE_PHIM_SAGA'
