export const GET_LENGTH_DATA_NGUOIDUNG = 'GET_LENGTH_DATA_NGUOIDUNG'
export const GET_DATA_NGUOIDUNG_THEOTRANG = 'GET_DATA_NGUOIDUNG_THEOTRANG'

export const FIND_DATA_NGUOIDUNG_THEOTRANG = 'FIND_DATA_NGUOIDUNG_THEOTRANG'

export const FIND_DATA_NGUOIDUNG = 'FIND_DATA_NGUOIDUNG'




//SAGA
export const GET_DATA_NGUOIDUNG_SAGA = 'GET_DATA_NGUOIDUNG_SAGA'
export const GET_DATA_NGUOIDUNG_THEOTRANG_SAGA = 'GET_DATA_NGUOIDUNG_THEOTRANG_SAGA'

export const FIND_DATA_NGUOIDUNG_SAGA = 'FIND_DATA_NGUOIDUNG_SAGA'
export const FIND_DATA_NGUOIDUNG_THEOTRANG_SAGA = 'FIND_DATA_NGUOIDUNG_THEOTRANG_SAGA'

export const DELETE_NGUOIDUNG_SAGA = 'DELETE_NGUOIDUNG_SAGA'

export const ADD_NGUOIDUNG_SAGA = 'ADD_NGUOIDUNG_SAGA'
export const UPDATE_NGUOIDUNG_SAGA = 'UPDATE_NGUOIDUNG_SAGA'
