export const GET_INFOR_THEATER = 'GET_INFOR_THEATER'
export const GET_DATA_CUM_THEATER = 'GET_DATA_CUM_THEATER'
export const RENDER_CUM_THEATER = 'RENDER_CUM_THEATER'
export const RENDER_CHITIET_RAP = 'RENDER_CHITIET_RAP'

//saga
export const GET_INFOR_THEATER_SAGA = 'GET_INFOR_THEATER_SAGA'
export const GET_DATA_CUM_THEATER_SAGA = 'GET_DATA_CUM_THEATER_SAGA'
export const RENDER_CUM_THEATER_SAGA = 'RENDER_CUM_THEATER_SAGA'

