export const GET_DATA_PHIM = 'GET_DATA_PHIM'
export const GET_DATA_CHITIETPHIM ='GET_DATA_CHITIETPHIM'

//saga
export const GET_DATA_PHIM_SAGA = 'GET_DATA_PHIM_SAGA'
export const GET_DATA_CHITIETPHIM_SAGA ='GET_DATA_CHITIETPHIM_SAGA'
